package dirv.chat.client.hangman;

public class Phrases {
    
    public static String[] all = new String[]{
            "anonymous class",
            "arraylist",
            "abstract factory pattern",
            "abstraction",
            "adapter pattern",
            "assert",
            "chain of responsibility pattern",
            "cohesion",
            "command pattern",
            "composite pattern",
            "composition",
            "default method",
            "dependency inversion principle",
            "encapsulation",
            "exception",
            "functional programming",
            "guard clause",
            "hashmap",
            "inheritance",
            "interface",
            "interface segregation principle",
            "iterator",
            "java",
            "law of demeter",
            "linked list",
            "liskov substitution principle",
            "method signature",
            "model view controller",
            "mutable reduction",
            "mutable state",
            "nullpointerexception",
            "observer pattern",
            "open/closed principle",
            "optional",
            "overload",
            "override",
            "polymorphism",
            "pure function",
            "queue",
            "recognized",
            "refactoring",
            "single responsibility principle",
            "stack",
            "switch",
            "systematic refactoring",
            "template method",
            "unsupportedoperationexception",
            "visitor pattern",
            "you ain't gonna need it"
    };

}
